### ISSUE TITLE
pubspec says sdk 1.8.0 is good enough but package_config requires 1.11

### ISSUE THREAD

**Issue by chalin** [dart-lang/analyzer_cli#30]
Running `pub get` on HEAD today (317635c120ba3d6a003e6041c0772eaf4a15a022) results in:
```shell
analyzer_cli > pub get
Resolving dependencies... (1.2s) 
Package package_config requires SDK version >=1.11.0-dev.0.0 <2.0.0 but the current SDK is 1.10.1.
```
Was it intensional to introduce a dependency on 1.11.x pre-release? The `pubspec.yaml` constraint is:
```yaml
  environment:
   sdk: '>=1.8.0 <2.0.0'
```
Either that needs to be updated or the version of `package_config` retrograded (or fixed to not require 1.11x).

**Comment by pq** [comment]
Ouch yes.  Spot on.  I'll take a look.

Thanks!

**Comment by seaneagan** [comment]
Why not just rely on `package_config`'s sdk constraint?  If `package_config` adds support for earlier SDK's in the future then this package's sdk constraints will need to be re-widened in order to support them as well.

**Comment by pq** [comment]
@seaneagan : that's a good question...  In fact that's just what we *were* doing.  That said, since we know we need to effectively bump this SDK dep, I don't think it hurts?  As for `package_config` retrograding I don't see that happening.  It's fundamentally built for (and on top of) SDK 1.11+ bits (language and library).

**Comment by pq** [comment]
See #32 for a lengthy discussion.  Net-net: lots of pushback to this proposed change.  If you feel strongly enough feel free to re-open and add your arguments to the fray!
